INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV001', 'BULAWAYO PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV002', 'HARARE PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV003', 'MANICALAND PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV004', 'MASHONALAND CENTRAL PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV005', 'MASHONALAND EAST PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV006', 'MASHONALAND WEST PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV007', 'MASVINGO PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV008', 'MATEBELELAND NORTH PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV009', 'MATEBELELAND SOUTH PROVINCE');
INSERT INTO public.region (region_id, province) VALUES ('REGION-PROV0010', 'MIDLANDS PROVINCE');
